apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks
  template:
    metadata:
      labels:
        app: eks
    spec:
      containers:
        - name: eks
          image: 339947993856.dkr.ecr.ap-northeast-2.amazonaws.com/potato:Yong
          ports:
            - containerPort: 8080
          imagePullPolicy: Alwaus
          env:
            - name: DATE
              value: 'DATE_STRING'